import {
  FileText,
  ShieldCheck,
  Cloud,
  Users,
  BadgeCheck,
  Rocket,
  Workflow,
  AppWindow,
  Lightbulb,
  Briefcase,
  Building2,
  Crown,
} from "lucide-react";

export const servicesSpanish = [
  {
    id: "essential-launch-guide",
    icon: FileText,
    name: "Guía Esencial de Lanzamiento",
    price: "200.00",
    priceNumber: 200,
  },
  {
    id: "express-launch",
    icon: ShieldCheck,
    name: "Lanzamiento Exprés",
    price: "350.00",
    priceNumber: 350,
  },
  {
    id: "exploratory-session",
    icon: Cloud,
    name: "Sesión Exploratoria",
    price: "480.00",
    priceNumber: 480,
  },
  {
    id: "initial-plan",
    icon: Users,
    name: "Plan Inicial",
    price: "900.00",
    priceNumber: 900,
  },
  {
    id: "digital-validation-pack",
    icon: BadgeCheck,
    name: "Paquete de Validación Digital",
    price: "2,100.00",
    priceNumber: 2100,
  },
  {
    id: "digital-launch-kit",
    icon: Rocket,
    name: "Kit de Lanzamiento Digital",
    price: "3,750.00",
    priceNumber: 3750,
  },
  {
    id: "digital-boost-package",
    icon: Workflow,
    name: "Paquete de Impulso Digital",
    price: "5,900.00",
    priceNumber: 5900,
  },
  {
    id: "digital-growth-package",
    icon: AppWindow,
    name: "Paquete de Crecimiento Digital",
    price: "7,350.00",
    priceNumber: 7350,
  },
  {
    id: "basic-startup-package",
    icon: Lightbulb,
    name: "Paquete Básico para Startups",
    price: "13,750.00",
    priceNumber: 13750,
  },
  {
    id: "starter-business-package",
    icon: Briefcase,
    name: "Paquete Empresarial Inicial",
    price: "22,500.00",
    priceNumber: 22500,
  },
  {
    id: "advanced-package-smes",
    icon: Building2,
    name: "Paquete Avanzado para PYMES",
    price: "34,000.00",
    priceNumber: 34000,
  },
  {
    id: "comprehensive-premium-package",
    icon: Crown,
    name: "Paquete Premium Integral",
    price: "55,000.00",
    priceNumber: 55000,
  },
];

export const servicesEnglish = [
  {
    id: "essential-launch-guide",
    icon: FileText,
    name: "Essential Launch Guide",
    price: "200.00",
    priceNumber: 200,
  },
  {
    id: "express-launch",
    icon: ShieldCheck,
    name: "Express Launch",
    price: "350.00",
    priceNumber: 350,
  },
  {
    id: "exploratory-session",
    icon: Cloud,
    name: "Exploratory Session",
    price: "480.00",
    priceNumber: 480,
  },
  {
    id: "initial-plan",
    icon: Users,
    name: "Initial Plan",
    price: "900.00",
    priceNumber: 900,
  },
  {
    id: "digital-validation-pack",
    icon: BadgeCheck,
    name: "Digital Validation Pack",
    price: "2,100.00",
    priceNumber: 2100,
  },
  {
    id: "digital-launch-kit",
    icon: Rocket,
    name: "Digital Launch Kit",
    price: "3,750.00",
    priceNumber: 3750,
  },
  {
    id: "digital-boost-package",
    icon: Workflow,
    name: "Digital Boost Package",
    price: "5,900.00",
    priceNumber: 5900,
  },
  {
    id: "digital-growth-package",
    icon: AppWindow,
    name: "Digital Growth Package",
    price: "7,350.00",
    priceNumber: 7350,
  },
  {
    id: "basic-startup-package",
    icon: Lightbulb,
    name: "Basic Startup Package",
    price: "13,750.00",
    priceNumber: 13750,
  },
  {
    id: "starter-business-package",
    icon: Briefcase,
    name: "Starter Business Package",
    price: "22,500.00",
    priceNumber: 22500,
  },
  {
    id: "advanced-package-smes",
    icon: Building2,
    name: "Advanced Package for SMEs",
    price: "34,000.00",
    priceNumber: 34000,
  },
  {
    id: "comprehensive-premium-package",
    icon: Crown,
    name: "Comprehensive Premium Package",
    price: "55,000.00",
    priceNumber: 55000,
  },
];